In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import time
import os
import pandas as pd
from random import randint
from bs4 import BeautifulSoup as bs
import requests
from tqdm import tqdm

In [74]:
masters_results = pd.DataFrame(columns = ['year', 'finish_position', 'player_name', 'to_par_score', 
            'round_1_score', 'round_2_score', 'round_3_score', 'round_4_score', 'total_score',
            'earnings'])

player_scorecards = pd.DataFrame(columns = ['year', 'player', 'round_num', 'hole_1', 'hole_2', 'hole_3', 'hole_4',
        'hole_5', 'hole_6', 'hole_7', 'hole_8', 'hole_9', 'front_total','hole_10', 'hole_11', 'hole_12', 'hole_13',
        'hole_14', 'hole_15', 'hole_16', 'hole_17', 'hole_18', 'back_total', 'total_score'])

In [83]:
row_count = 0
score_count = 0

for year in trange(2016, 1936, -1):
    url = 'http://www.augusta.com/masters/historic/leaderboards/' + str(year) + 'leaderboard.shtml'
    
    time.sleep(1)
    response = requests.get(url)
    soup = bs(response.content, 'lxml')
    
    tr_ls = soup.findAll('table')[0].findAll('tr')

   
    for t, tr in enumerate(tr_ls[1:]):
        td = tr.findAll('td')
        cell_ls = [year]
        for c, cell in enumerate(td):
            cell_ls.append(cell.text.replace('\n', '').replace('\t',''))
        masters_results.loc[row_count] = cell_ls
        row_count += 1
    
    a_tags = soup.find_all('a')

    player_urls = []
    for a_tag in a_tags:
        if 'historic/players/hbh' in a_tag.attrs['href']:
            player_urls.append(a_tag)
            
    for player in player_urls:
        player_name = player.text
        player_url = 'http://www.augusta.com' + player.attrs['href']
        
        time.sleep(1)
        player_response = requests.get(player_url)

        player_soup = bs(player_response.content, 'lxml')
        
        player_tables = player_soup.findAll('table')

        for t, tr in enumerate(player_tables[0].findAll('tr', {'id': ''})):
            td = tr.findAll('td')
            td_0 = td[0].text.replace('\n','').replace('\t','')
            if td_0[:2] == 'Rd':
                rd = td_0[-1]
                cell_ls = [year, player_name, rd]
                for cell in td[1:]:
                    temp_cell = cell.text.replace('\n','').replace('\t','')
                    cell_ls.append(temp_cell)
                player_scorecards.loc[score_count] = cell_ls
                score_count += 1

Danny Willett
Jordan Spieth
Lee Westwood
Paul Casey
J.B. Holmes
Dustin Johnson
Matthew Fitzpatrick

KeyboardInterrupt:

In [85]:
masters_results

,year,finish_position,player_name,to_par_score,round_1_score,round_2_score,round_3_score,round_4_score,total_score,earnings
0,2016.0,1,Danny Willett,-5,70,74,72,67,283,"$1,800,000"
1,2016.0,T2,Jordan Spieth,-2,66,74,73,73,286,"$880,000"
2,2016.0,T2,Lee Westwood,-2,71,75,71,69,286,"$880,000"
3,2016.0,T4,Paul Casey,-1,69,77,74,67,287,"$413,333"
4,2016.0,T4,J.B. Holmes,-1,72,73,74,68,287,"$413,333"
5,2016.0,T4,Dustin Johnson,-1,73,71,72,71,287,"$413,333"
6,2016.0,T7,Matthew Fitzpatrick,E,71,76,74,67,288,"$311,667"
7,2016.0,T7,Soren Kjeldsen,E,69,74,74,71,288,"$311,667"
8,2016.0,T7,Hideki Matsuyama,E,71,72,72,73,288,"$311,667"
9,2016.0,T10,Daniel Berger,+1,73,71,74,71,289,"$230,000"
10,2016.0,T10,Jason Day,+1,72,73,71,73,289,"$230,000"
11,2016.0,T10,Rory McIlroy,+1,70,71,77,71,289,"$230,000"
12,2016.0,T10,Justin Rose,+1,69,77,73,70,289,"$230,000"
13,2016.0,T10,Brandt Snedeker,+1,71,72,74,72,289,"$230,000"
14,2016.0,T15,Kiradech Aphibarnrat,+3,72,72,77,70,291,"$175,000"
15,2016.0,T15,Louis Oosthuizen,+3,72,77,71,71,291,"$175,000"
16,2016.0,T17,Rafa Cabrera-Bello,+4,74,73,75,70,292,"$145,000"
17,2016.0,T17,Emiliano Grillo,+4,71,75,74,72,292,"$145,000"
18,2016.0,T17,Billy Horschel,+4,70,77,73,72,292,"$145,000"
19,2016.0,T17,Danny Lee,+4,68,74,79,71,292,"$145,000"
20,2016.0,T21,Bryson DeChambeau,+5,72,72,77,72,293,-
21,2016.0,T21,Jamie Donaldson,+5,74,72,75,72,293,"$116,000"
22,2016.0,T21,Brooks Koepka,+5,73,72,76,72,293,"$116,000"
23,2016.0,T24,Angel Cabrera,+6,73,73,73,75,294,"$89,000"
24,2016.0,T24,Bill Haas,+6,75,74,72,73,294,"$89,000"
25,2016.0,T24,Matt Kuchar,+6,75,73,72,74,294,"$89,000"
26,2016.0,T24,Bernhard Langer,+6,72,73,70,79,294,"$89,000"
27,2016.0,T24,Henrik Stenson,+6,72,75,78,69,294,"$89,000"
28,2016.0,T29,Charley Hoffman,+7,71,77,73,74,295,"$68,000"
29,2016.0,T29,Smylie Kaufman,+7,73,72,69,81,295,"$68,000"
30,2016.0,T29,Scott Piercy,+7,70,72,79,74,295,"$68,000"
31,2016.0,T29,Webb Simpson,+7,77,72,74,72,295,"$68,000"
32,2016.0,T29,Jimmy Walker,+7,71,75,74,75,295,"$68,000"
33,2016.0,T34,Sergio Garcia,+8,69,75,81,71,296,"$56,500"
34,2016.0,T34,Kevin Streelman,+8,71,75,79,71,296,"$56,500"
35,2016.0,T34,Bernd Wiesberger,+8,73,72,79,72,296,"$56,500"
36,2016.0,T37,Kevin Kisner,+9,77,72,76,72,297,"$50,250"
37,2016.0,T37,Bubba Watson,+9,75,75,76,71,297,"$50,250"
38,2016.0,T39,Romain Langasque,+10,74,73,83,68,298,-
39,2016.0,T39,Shane Lowry,+10,68,76,79,75,298,"$46,000"
40,2016.0,T39,Justin Thomas,+10,76,73,78,71,298,"$46,000"
41,2016.0,T42,Victor Dubuisson,+11,73,76,76,74,299,"$37,000"
42,2016.0,T42,Harris English,+11,74,73,76,76,299,"$37,000"
43,2016.0,T42,Anirban Lahiri,+11,76,73,75,75,299,"$37,000"
44,2016.0,T42,Davis Love III,+11,73,73,76,77,299,"$37,000"
45,2016.0,T42,Troy Merritt,+11,74,71,79,75,299,"$37,000"
46,2016.0,T42,Adam Scott,+11,76,72,75,76,299,"$37,000"
47,2016.0,T42,Chris Wood,+11,72,73,75,79,299,"$37,000"
48,2016.0,T49,Martin Kaymer,+12,74,75,79,72,300,"$27,467"
49,2016.0,T49,Ian Poulter,+12,69,78,82,71,300,"$27,467"
50,2016.0,T49,Patrick Reed,+12,76,73,75,76,300,"$27,467"
51,2016.0,T52,Keegan Bradley,+13,74,73,77,77,301,"$24,900"
52,2016.0,T52,Larry Mize,+13,76,73,78,74,301,"$24,900"
53,2016.0,54,Hunter Mahan,+14,73,75,78,76,302,"$24,000"
54,2016.0,T55,Kevin Na,+15,72,74,85,72,303,"$23,400"
55,2016.0,T55,Cameron Smith,+15,74,73,82,74,303,"$23,400"
56,2016.0,57,Thongchai Jaidee,+19,72,76,81,78,307,"$23,000"

In [17]:
a_tags = soup.find_all('a')

player_urls = []
for a_tag in a_tags:
    if 'historic/players/hbh' in a_tag.attrs['href']:
        player_urls.append(a_tag)
        
player_urls

[<a href="/masters/historic/players/hbh/2007_hbh11981.shtml">Zach Johnson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh209.shtml">Retief Goosen</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1191.shtml">Rory Sabbatini</a>,
 <a href="/masters/historic/players/hbh/2007_hbh184.shtml">Tiger Woods</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1159.shtml">Jerry Kelly</a>,
 <a href="/masters/historic/players/hbh/2007_hbh3185.shtml">Justin Rose</a>,
 <a href="/masters/historic/players/hbh/2007_hbh197.shtml">Stuart Appleby</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1508.shtml">Padraig Harrington</a>,
 <a href="/masters/historic/players/hbh/2007_hbh220.shtml">David Toms</a>,
 <a href="/masters/historic/players/hbh/2007_hbh6962.shtml">Paul Casey</a>,
 <a href="/masters/historic/players/hbh/2007_hbh3128.shtml">Luke Donald</a>,
 <a href="/masters/historic/players/hbh/2007_hbh4483.shtml">Vaughn Taylor</a>,
 <a href="/masters/historic/players/hbh/2007_hbh205.shtml">Tim Clark</a>,
 <a href="/masters/historic/players/hbh/2007_hbh130.shtml">Jim Furyk</a>,
 <a href="/masters/historic/players/hbh/2007_hbh5173.shtml">Ian Poulter</a>,
 <a href="/masters/historic/players/hbh/2007_hbh171.shtml">Vijay Singh</a>,
 <a href="/masters/historic/players/hbh/2007_hbh113.shtml">Stewart Cink</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1261.shtml">Tom Pernice Jr.</a>,
 <a href="/masters/historic/players/hbh/2007_hbh8421.shtml">Henrik Stenson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh111.shtml">Mark Calcavecchia</a>,
 <a href="/masters/historic/players/hbh/2007_hbh15341.shtml">Lucas Glover</a>,
 <a href="/masters/historic/players/hbh/2007_hbh4036.shtml">John Rollins</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1209.shtml">Mike Weir</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1495.shtml">Stephen Ames</a>,
 <a href="/masters/historic/players/hbh/2007_hbh149.shtml">Phil Mickelson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh3086.shtml">Geoff Ogilvy</a>,
 <a href="/masters/historic/players/hbh/2007_hbh2721.shtml">K.J. Choi</a>,
 <a href="/masters/historic/players/hbh/2007_hbh144.shtml">Davis Love III</a>,
 <a href="/masters/historic/players/hbh/2007_hbh5164.shtml">Adam Scott</a>,
 <a href="/masters/historic/players/hbh/2007_hbh116.shtml">Fred Couples</a>,
 <a href="/masters/historic/players/hbh/2007_hbh4966.shtml">Charles Howell</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1461.shtml">Robert Karlsson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1266.shtml">Scott Verplank</a>,
 <a href="/masters/historic/players/hbh/2007_hbh182.shtml">Lee Westwood</a>,
 <a href="/masters/historic/players/hbh/2007_hbh8502.shtml">Dean Wilson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh13314.shtml">Yong-Eun Yang</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1525.shtml">Angel Cabrera</a>,
 <a href="/masters/historic/players/hbh/2007_hbh2941.shtml">J.J. Henry</a>,
 <a href="/masters/historic/players/hbh/2007_hbh211.shtml">Tim Herron</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1558.shtml">Rod Pampling</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1539.shtml">Jeev Singh</a>,
 <a href="/masters/historic/players/hbh/2007_hbh4127.shtml">Brett Wetterich</a>,
 <a href="/masters/historic/players/hbh/2007_hbh145.shtml">Sandy Lyle</a>,
 <a href="/masters/historic/players/hbh/2007_hbh13681.shtml">Bradley Dredge</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1498.shtml">David Howell</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1487.shtml">Miguel Angel Jimenez</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1516.shtml">Shingo Katayama</a>,
 <a href="/masters/historic/players/hbh/2007_hbh159.shtml">Jose-Maria Olazabal</a>,
 <a href="/masters/historic/players/hbh/2007_hbh172.shtml">Jeff Sluman</a>,
 <a href="/masters/historic/players/hbh/2007_hbh173.shtml">Craig Stadler</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1341.shtml">Brett Quigley</a>,
 <a href="/masters/historic/players/hbh/2007_hbh3986.shtml">Aaron Baddeley</a>,
 <a href="/masters/historic/players/hbh/2007_hbh11261.shtml">Carl Pettersson</a>,
 <a href="/masters/historic/players/hbh/2007_hbh1175.shtml">Rich Beem</a>,
 <a href="/masters/historic/players/hbh/2007_hbh117.shtml">Ben Crenshaw</a>,
 <a href="/masters/historic/players/hbh/2007_hbh5561.shtml">Niclas Fasth</a>,
 <a href="/masters/historic/players/hbh/2007_hbh2343.shtml">Trevor Immelman</a>,
 <a href="/masters/historic/players/hbh/2007_hbh5501.shtml">Arron Oberholser</a>,
 <a href="/masters/historic/players/hbh/2007_hbh221.shtml">Billy Mayfair</a>,
 <a href="/masters/historic/players/hbh/2007_hbh186.shtml">Fuzzy Zoeller</a>]

In [66]:
tr_ls = soup.findAll('table')[0].findAll('tr')

row_count = 0
for t, tr in enumerate(tr_ls[1:]):
    td = tr.findAll('td')
    cell_ls = [year]
    for c, cell in enumerate(td):
        cell_ls.append(cell.text.replace('\n', '').replace('\t',''))
    masters_results.loc[row_count] = cell_ls
    row_count += 1
    
masters_results

,year,finish_position,player_name,to_par_score,round_1_score,round_2_score,round_3_score,round_4_score,total_score,earnings
0,2007,1,Zach Johnson,+1,71,73,76,69,289,"$1,305,000"
1,2007,T2,Retief Goosen,+3,76,76,70,69,291,"$541,333"
2,2007,T2,Rory Sabbatini,+3,73,76,73,69,291,"$541,333"
3,2007,T2,Tiger Woods,+3,73,74,72,72,291,"$541,333"
4,2007,T5,Jerry Kelly,+4,75,69,78,70,292,"$275,500"
5,2007,T5,Justin Rose,+4,69,75,75,73,292,"$275,500"
6,2007,T7,Stuart Appleby,+5,75,70,73,75,293,"$233,812"
7,2007,T7,Padraig Harrington,+5,77,68,75,73,293,"$233,812"
8,2007,9,David Toms,+6,70,78,74,72,294,"$210,250"
9,2007,T10,Paul Casey,+7,79,68,77,71,295,"$181,250"
10,2007,T10,Luke Donald,+7,73,74,75,73,295,"$181,250"
11,2007,T10,Vaughn Taylor,+7,71,72,77,75,295,"$181,250"
12,2007,T13,Tim Clark,+8,71,71,80,74,296,"$135,937"
13,2007,T13,Jim Furyk,+8,75,71,76,74,296,"$135,937"
14,2007,T13,Ian Poulter,+8,75,75,76,70,296,"$135,937"
15,2007,T13,Vijay Singh,+8,73,71,79,73,296,"$135,937"
16,2007,T17,Stewart Cink,+9,77,75,75,70,297,"$108,750"
17,2007,T17,Tom Pernice Jr.,+9,75,72,79,71,297,"$108,750"
18,2007,T17,Henrik Stenson,+9,72,76,77,72,297,"$108,750"
19,2007,T20,Mark Calcavecchia,+10,76,71,78,73,298,"$84,462"
20,2007,T20,Lucas Glover,+10,74,71,79,74,298,"$84,462"
21,2007,T20,John Rollins,+10,77,74,76,71,298,"$84,462"
22,2007,T20,Mike Weir,+10,75,72,80,71,298,"$84,462"
23,2007,T24,Stephen Ames,+11,76,74,77,72,299,"$63,800"
24,2007,T24,Phil Mickelson,+11,76,73,73,77,299,"$63,800"
25,2007,T24,Geoff Ogilvy,+11,75,70,81,73,299,"$63,800"
26,2007,T27,K.J. Choi,+12,75,75,74,76,300,"$53,650"
27,2007,T27,Davis Love III,+12,72,77,77,74,300,"$53,650"
28,2007,T27,Adam Scott,+12,74,78,76,72,300,"$53,650"
29,2007,T30,Fred Couples,+13,76,76,78,71,301,"$43,085"
30,2007,T30,Charles Howell,+13,75,77,75,74,301,"$43,085"
31,2007,T30,Robert Karlsson,+13,77,73,79,72,301,"$43,085"
32,2007,T30,Scott Verplank,+13,73,77,76,75,301,"$43,085"
33,2007,T30,Lee Westwood,+13,79,73,72,77,301,"$43,085"
34,2007,T30,Dean Wilson,+13,75,72,76,78,301,"$43,085"
35,2007,T30,Yong-Eun Yang,+13,75,74,78,74,301,"$43,085"
36,2007,T37,Angel Cabrera,+14,77,75,79,71,302,"$31,900"
37,2007,T37,J.J. Henry,+14,71,78,77,76,302,"$31,900"
38,2007,T37,Tim Herron,+14,72,75,83,72,302,"$31,900"
39,2007,T37,Rod Pampling,+14,77,75,74,76,302,"$31,900"
40,2007,T37,Jeev Singh,+14,72,75,76,79,302,"$31,900"
41,2007,T37,Brett Wetterich,+14,69,73,83,77,302,"$31,900"
42,2007,43,Sandy Lyle,+15,79,73,80,71,303,"$26,825"
43,2007,T44,Bradley Dredge,+16,75,70,76,83,304,"$22,533"
44,2007,T44,David Howell,+16,70,75,82,77,304,"$22,533"
45,2007,T44,Miguel Angel Jimenez,+16,79,73,76,76,304,"$22,533"
46,2007,T44,Shingo Katayama,+16,79,72,80,73,304,"$22,533"
47,2007,T44,Jose-Maria Olazabal,+16,74,75,78,77,304,"$22,533"
48,2007,T49,Jeff Sluman,+17,76,75,79,75,305,"$18,560"
49,2007,T49,Craig Stadler,+17,74,73,79,79,305,"$18,560"
50,2007,51,Brett Quigley,+18,76,76,79,75,306,"$17,835"
51,2007,T52,Aaron Baddeley,+19,79,72,76,80,307,"$17,255"
52,2007,T52,Carl Pettersson,+19,76,76,79,76,307,"$17,255"
53,2007,54,Rich Beem,+20,71,81,75,81,308,"$16,820"
54,2007,T55,Ben Crenshaw,+21,76,74,84,75,309,"$16,530"
55,2007,T55,Niclas Fasth,+21,77,75,77,80,309,"$16,530"
56,2007,T55,Trevor Immelman,+21,74,77,81,77,309,"$16,530"
57,2007,58,Arron Oberholser,+22,74,76,84,76,310,"$16,240"
58,2007,59,Billy Mayfair,+23,76,75,83,77,311,"$16,095"
59,2007,60,Fuzzy Zoeller,+25,74,78,79,82,313,"$15,950"

In [79]:
player_url = 'http://www.augusta.com' + player_urls[3].attrs['href']
player_response = requests.get(player_url)

player_soup = bs(player_response.content, 'lxml')

In [81]:
player_tables = player_soup.findAll('table')

#score_count = 0
for t, tr in enumerate(player_tables[0].findAll('tr', {'id': ''})):
    td = tr.findAll('td')
    td_0 = td[0].text.replace('\n','').replace('\t','')
    if td_0[:2] == 'Rd':
        rd = td_0[-1]
        cell_ls = [year, player_name, rd]
        for cell in td[1:]:
            temp_cell = cell.text.replace('\n','').replace('\t','')
            cell_ls.append(temp_cell)
        player_scorecards.loc[score_count] = cell_ls
        score_count += 1

In [82]:
player_scorecards

,year,player,round,hole_1,hole_2,hole_3,hole_4,hole_5,hole_6,hole_7,...,hole_11,hole_12,hole_13,hole_14,hole_15,hole_16,hole_17,hole_18,back_total,total_score
0,2007,Zach Johnson,4,5,4,3,3,5,3,4,...,4,3,4,3,5,2,5,4,34,69
1,2007,Zach Johnson,3,4,5,4,3,5,3,4,...,5,4,5,4,4,4,4,4,38,76
2,2007,Zach Johnson,2,4,4,3,3,5,3,4,...,5,3,4,4,5,4,5,5,39,73
3,2007,Zach Johnson,1,5,4,4,3,4,3,4,...,4,3,4,4,4,4,4,4,36,71
4,2007,Tiger Woods,4,5,4,4,3,4,4,4,...,4,3,3,4,5,3,4,4,35,72
5,2007,Tiger Woods,3,4,5,3,3,4,3,4,...,4,4,4,4,5,3,5,5,38,72
6,2007,Tiger Woods,2,5,5,4,4,4,3,5,...,5,4,5,4,4,3,3,4,35,74
7,2007,Tiger Woods,1,4,5,4,3,4,3,5,...,4,3,4,4,4,3,5,5,36,73

In [80]:
player_url

'http://www.augusta.com/masters/historic/players/hbh/2007_hbh184.shtml'